library(dplyr)
library(purrr)
library(tidyr)
library(deSolve)
library(shellpipes)
loadEnvironments()
ElrangMomentsFile<-read.csv("Codes/ErlangMoments.csv")
res_mat<- rbind(ElrangMomentsFile, res_mat)
write.csv(res_mat, file = "Codes/ErlangMoments.csv", row.names = FALSE)
saveEnvironment()
